table 'DimProvincia 2'
	lineageTag: aab9f03e-b04b-4cbb-9d92-02dd6646d4d2

	column IDProvincia
		dataType: int64
		formatString: 0
		lineageTag: ab1b155b-7eea-49c0-9aa5-0e2c3124306e
		summarizeBy: sum
		sourceColumn: IDProvincia

		annotation SummarizationSetBy = Automatic

	column Provincia
		dataType: string
		lineageTag: 400d61d6-6969-4e78-84f7-29534cf2c239
		summarizeBy: none
		sourceColumn: Provincia
		sortByColumn: IDProvincia

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column País
		dataType: string
		lineageTag: 62325894-4722-48e0-8c22-44fd4dd4b1ae
		summarizeBy: none
		sourceColumn: País

		annotation SummarizationSetBy = Automatic

	partition 'DimProvincia 2' = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUQpOzCtJVHBLBTIdi9JT80oy8xKVYnWilYyAIq55JUWpCkGH1+YXY8gbQzQreJUm5mFImsBNdi4qrUKVjgUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [IDProvincia = _t, Provincia = _t, País = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"IDProvincia", Int64.Type}, {"Provincia", type text}, {"País", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

